DROP TABLE IF EXISTS profiles;

CREATE TABLE profiles
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    avatar VARCHAR(500)
);

INSERT INTO profiles (first_name, last_name, email, phone, avatar)
VALUES ('Ada', 'Lovelace', 'ada@example.com', '+380501112233', 'ada.png');
